"""Typed, provider-independent identifiers."""

from dataclasses import dataclass

from fra.domain.errors import DomainValidationError


@dataclass(frozen=True, slots=True)
class DomainId:
    """Base value for an ID generated by FRA rather than an external provider."""

    value: str

    def __post_init__(self) -> None:
        value = self.value.strip()
        if not value or any(character.isspace() for character in value):
            raise DomainValidationError("domain IDs must be non-empty and contain no whitespace")
        object.__setattr__(self, "value", value)

    def __str__(self) -> str:
        return self.value


@dataclass(frozen=True, slots=True)
class InstrumentId(DomainId):
    """Provider-independent instrument identity."""


@dataclass(frozen=True, slots=True)
class ResearchRunId(DomainId):
    """Research run identity."""


@dataclass(frozen=True, slots=True)
class MandateId(DomainId):
    """Research mandate identity."""


@dataclass(frozen=True, slots=True)
class EvidenceId(DomainId):
    """Normalized evidence identity."""


@dataclass(frozen=True, slots=True)
class ClaimId(DomainId):
    """Research claim identity."""


@dataclass(frozen=True, slots=True)
class SignalId(DomainId):
    """Signal aggregate identity."""


@dataclass(frozen=True, slots=True)
class StageId(DomainId):
    """Agent-stage identity."""
